#	$NetBSD$

NOOBJ=	# defined

.include <bsd.own.mk>

.if ${MKSHARE} != "no"
FILES=	cingular3G cingular3G.chat
FILES+=	cosmote3G cosmote3G.chat
FILES+=	telus telus.chat
FILESDIR=/usr/share/examples/pppd
.endif

.include <bsd.prog.mk>
