#	$NetBSD$

# Install userland OpenCrypto Framework (OCF) headers in /usr/include/crypto,
# to keep our userland API (openssl, apache, ...) compatible with the
# original OpenBSD API.

INCSDIR=/usr/include/crypto

INCS=	cryptodev.h

.include <bsd.kinc.mk>
