#	$NetBSD$

SUBDIR=
SUBDIR+=	bootfloppy
SUBDIR+=	bootfloppy-com
# SUBDIR+=	bootfloppy-big
# These are all rather archaic...
# SUBDIR+=	bootfloppy-ps2
# SUBDIR+=	bootfloppy-small
# SUBDIR+=	bootfloppy-tiny
# SUBDIR+=	rescue-tiny

TARGETS+=	release

.include <bsd.subdir.mk>
