#	$NetBSD$

.include <bsd.own.mk>

GETTEXTTOP=${NETBSDSRCDIR}/gnu/dist/gettext
TEXINFO=	gettext.texi
INFOFLAGS=	-I${GETTEXTTOP}/gettext-tools/doc \
    -I${GETTEXTTOP}/gettext-runtime/doc

.include <bsd.info.mk>

.PATH: ${GETTEXTTOP}/gettext-tools/doc
