#	$NetBSD$

NOOBJ=	# defined

.include <bsd.own.mk>

.if ${MKSHARE} != "no"
FILES=	holidays.D.SH isdnd.rates.A isdnd.rates.D isdnd.rates.F \
	isdnd.rates.L isdnd.rates.UK.BT isdnd.rc.sample
FILESDIR=/usr/share/examples/isdn
.endif

.include <bsd.prog.mk>
