#	$NetBSD$

MAKEKEYSDIR!=	cd ${NETBSDSRCDIR}/x11/tools/makekeys && ${PRINTOBJDIR}
MAKEKEYS=	${MAKEKEYSDIR}/makekeys

${MAKEKEYS}:
	(cd ${NETBSDSRCDIR}/x11/tools/makekeys && ${MAKE})

DPSRCS+=	ks_tables.h
CLEANFILES+=	ks_tables.h

ks_tables.h: ${MAKEKEYS} ${X11SRCDIR.xc}/include/keysymdef.h
	${_MKTARGET_CREATE}
	rm -f ${.TARGET}
	${MAKEKEYS} < ${X11SRCDIR.xc}/include/keysymdef.h > ${.TARGET}
