#	$NetBSD$

.include <bsd.own.mk>

.PATH:	${X11SRCDIR.xc}/extras/fontconfig/fontconfig

INCSDIR=${X11INCDIR}/fontconfig

INCS=	fcfreetype.h fcprivate.h fontconfig.h

.include <bsd.x11.mk>
.include <bsd.prog.mk>
