#	$NetBSD$
#

.include <bsd.own.mk>

TESTSDIR=       ${TESTSBASE}/usr.bin

TESTS_SUBDIRS=	awk basename bzip2 cc cmp config cut \
		diff dirname find grep gzip id infocmp jot m4 make mkdep \
		nbperf netpgpverify pr rump_server shmif_dumpbus sdiff \
		sed sort tmux tr unifdef xlint

.include <bsd.test.mk>
