#	$NetBSD$

BOOTFILE=		cdboot.lif

CDMAKEFSOPTIONS=	generic-bootimage=cdrom/${BOOTFILE}
CDINSTKERNEL=		../../kernel
CDKERNELS=		netbsd-RAMDISK	netbsd	# from ../instkernel

prepare_md_post:
	${RM} -f cdrom/${BOOTFILE}
	${TOOL_HP700MKBOOT} ${DESTDIR}/usr/mdec/cdboot cdrom/${BOOTFILE}
