#	$NetBSD$

LIB=		xtrap
.PATH:		${X11SRCDIR.xc}/programs/Xserver/XTrap

SRCS+=		xtrapddmi.c xtrapdi.c xtrapdiswp.c xtrapditbl.c

CPPFLAGS+=	-I${X11SRCDIR.xc}/programs/Xserver/include \
		-I${XSERVERINCDIR} \
		-I${DESTDIR}${X11INCDIR}/X11/extensions \
		-I${DESTDIR}${X11INCDIR}/X11 \
		-I${X11SRCDIR.xc}/programs/Xserver/Xext

.include <bsd.x11.mk>
LIBDIR=	${XMODULEDIR}
.include <bsd.lib.mk>
