#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: bootparams
# REQUIRE: rpcbind DAEMON
# BEFORE:  LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="bootparamd"
rcvar=$name
command="/usr/sbin/rpc.${name}"
required_files="/etc/bootparams"

load_rc_config $name
run_rc_command "$1"
