#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: devpubd
# REQUIRE: DAEMON
# BEFORE:  LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="devpubd"
rcvar=$name
command="/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
