#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: hostapd
# REQUIRE: mountcritremote

$_rc_subr_loaded . /etc/rc.subr

name="hostapd"
rcvar=$name
command="/usr/sbin/hostapd"
required_files="/etc/hostapd.conf"

load_rc_config $name
run_rc_command "$1"
