#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: httpd
# REQUIRE: LOGIN
# KEYWORD: shutdown

$_rc_subr_loaded . /etc/rc.subr

name="httpd"
rcvar=$name
command="/usr/libexec/${name}"

load_rc_config $name

httpd_wwwuser_arg=${httpd_wwwuser:+-U \'$httpd_wwwuser\'}
command_args="$httpd_wwwuser_arg -b '$httpd_wwwdir'"
required_dirs="$httpd_wwwdir"

run_rc_command "$1"
