#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: ipmon
# REQUIRE: syslogd
# BEFORE:  SERVERS

$_rc_subr_loaded . /etc/rc.subr

name="ipmon"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
