#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: isibootd
# REQUIRE: DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="isibootd"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/ethers"

load_rc_config $name
run_rc_command "$1"
