#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: ldconfig
# REQUIRE: mountall
# BEFORE:  DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="ldconfig"
rcvar="ldconfig"
ldconfig_command="/sbin/ldconfig"
start_cmd="ldconfig_start"
stop_cmd=":"

ldconfig_start()
{
	if [ -f ${ldconfig_command} ]; then
		echo "Creating a.out runtime link editor directory cache."
		${ldconfig_command} ${rc_flags}
	fi
}

load_rc_config $name
run_rc_command "$1"
