#!/bin/sh
#
# $NetBSD$
#

# REQUIRE: DAEMON
# PROVIDE: local
# BEFORE:  LOGIN
# KEYWORD: shutdown

$_rc_subr_loaded . /etc/rc.subr

name="local"
start_cmd="local_start"
stop_cmd="local_stop"

local_start()
{
	if [ -f /etc/rc.local ]; then
		. /etc/rc.local
	fi
}

local_stop()
{
	if [ -f /etc/rc.shutdown.local ]; then
		. /etc/rc.shutdown.local
	fi
}

load_rc_config $name
run_rc_command "$1"
