#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: LOGIN
# REQUIRE: DAEMON

#	This is a dummy dependency to ensure user services such as xdm,
#	inetd, cron and kerberos are started after everything else, incase
#	the administrator has increased the system security level and
#	wants to delay user logins until the system is (almost) fully
#	operational.
