#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: lpd
# REQUIRE: DAEMON
# BEFORE:  LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="lpd"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/printcap"

load_rc_config $name
run_rc_command "$1"
