#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: mdnsd
# REQUIRE: SERVERS

$_rc_subr_loaded . /etc/rc.subr

name="mdnsd"
rcvar=$name
command="/usr/sbin/$name"
pidfile="/var/run/mdnsd/${name}.pid"
start_precmd="mdnsd_precmd"

mdnsd_precmd()
{
    if [ ! -d /var/run/mdnsd ]; then
        mkdir -p -m 755 /var/run/mdnsd
    fi
    chown _mdnsd:_mdnsd /var/run/mdnsd
}
                                                        
load_rc_config $name
run_rc_command "$1"
