#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: mountd
# REQUIRE: NETWORKING mountall rpcbind quota

$_rc_subr_loaded . /etc/rc.subr

name="mountd"
rcvar=$name
command="/usr/sbin/${name}"
required_files="/etc/exports"
start_precmd="mountd_precmd"
extra_commands="reload"

mountd_precmd()
{
	rm -f /var/db/mountdtab
	( umask 022 ; > /var/db/mountdtab )
	return 0
}

load_rc_config $name
run_rc_command "$1"
