#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: nfsd
# REQUIRE: rpcbind mountd

$_rc_subr_loaded . /etc/rc.subr

name="nfsd"
rcvar="nfs_server"
command="/usr/sbin/${name}"
required_vars="mountd rpcbind"

load_rc_config $name
load_rc_config_var rpcbind rpcbind
load_rc_config_var mountd mountd
run_rc_command "$1"
