#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: powerd
# REQUIRE: DAEMON
# BEFORE:  LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="powerd"
rcvar=$name
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
