#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: quota
# REQUIRE: mountall
# BEFORE:  DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="quota"
rcvar="quota"
start_cmd="quota_start"
stop_cmd="/usr/sbin/quotaoff -a"

quota_start()
{
	echo -n "Checking quotas:"
	/usr/sbin/quotacheck -a
	echo " done."
	/usr/sbin/quotaon -a
}

load_rc_config $name
run_rc_command "$1"
