#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: ike
# REQUIRE: isdnd kdc ppp
# BEFORE:  SERVERS
# KEYWORD: shutdown

$_rc_subr_loaded . /etc/rc.subr

name="racoon"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/racoon/racoon.conf"

load_rc_config $name
run_rc_command "$1"
