#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd named ppp

$_rc_subr_loaded . /etc/rc.subr

name="rpcbind"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
