#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: rtsold
# REQUIRE: network mountcritlocal
# BEFORE:  NETWORKING

$_rc_subr_loaded . /etc/rc.subr

name="rtsold"
rcvar=$name
command="/usr/sbin/${name}"
start_precmd="rtsold_precmd"

rtsold_precmd()
{
	if [ "$ip6mode" != "autohost" ]; then
		warn "\$ip6mode must be set to 'autohost' to use ${name}."
		return 1
	fi
}

load_rc_config $name
run_rc_command "$1"
