#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: tpctl
# REQUIRE: DAEMON wscons
# BEFORE:  LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="tpctl"
rcvar=$name
start_cmd="run_tpctl"
stop_cmd=":"

run_tpctl()
{
	echo "Calibrating touch panel..."
	/usr/sbin/${name} $rc_flags
}

load_rc_config $name
run_rc_command "$1"
