#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: yppasswdd
# REQUIRE: rpcbind ypserv ypbind
# BEFORE:  LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="yppasswdd"
rcvar=$name
command="/usr/sbin/rpc.${name}"
required_vars="rpcbind ypserv"
start_precmd="yppasswdd_precmd"

yppasswdd_precmd()
{
	_domain=$(domainname)
	if [ -z "$_domain" ]; then
		warn "domainname(1) is not set."
		return 1
	fi
}

load_rc_config $name
load_rc_config_var rpcbind rpcbind
load_rc_config_var ypserv ypserv
run_rc_command "$1"
