#!/bin/sh
#
# $NetBSD$
#

# PROVIDE: ypserv
# REQUIRE: rpcbind

$_rc_subr_loaded . /etc/rc.subr

name="ypserv"
rcvar=$name
command="/usr/sbin/${name}"
required_vars="rpcbind"
start_precmd="ypserv_precmd"

ypserv_precmd()
{
	if [ ! -d /var/yp/. ]; then
		warn "/var/yp is not a directory."
		return 1
	fi
}

load_rc_config $name
load_rc_config_var rpcbind rpcbind
run_rc_command "$1"
