#	$NetBSD$
#

.include <bsd.own.mk>

RUMPKERNCOMPS=	crypto time tty z

.if ${MKSLJIT} != "no"
RUMPKERNCOMPS+=	sljit
.endif

.if ${MKZFS} != "no"
RUMPKERNCOMPS+=    solaris
.endif

.for var in ${RUMPKERNCOMPS}
RUMPKERNLIBS+=lib${var}
RUMPKERNLDADD+=-lrumpkern_${var}
.endfor
