#	$NetBSD$

XMODULEDIR=	${X11ROOTDIR}/lib/modules/extensions

.include "../../../Makefile.serverlib"

.include <bsd.own.mk>

.PATH:		${X11SRCDIR.xc}/programs/Xserver/GL
SRCS=		glxmodule.c

.include "../Makefile.glx"
