#	$NetBSD$
#

.include <bsd.own.mk>

RUMPNETCOMP=	agr bridge net net80211 netbt netinet netinet6 netmpls npf
RUMPNETCOMP+=	local shmif

.if ${RUMP_VIRTIF:Uyes} == "yes"
RUMPNETCOMP+=	virtif
.endif

RUMPNETSOCKIN=	sockin

.for var in ${RUMPNETCOMP}
RUMPNETLIBS+=lib${var}
RUMPNETLDADD+=-lrumpnet_${var}
.endfor

.for var in ${RUMPNETSOCKIN}
RUMPNETLIBS+=lib${var}
.endfor
