#	$NetBSD$
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

# Missing: connectives, words

NOOBJ=	# defined

FILES=	README propernames web2 web2a
FILESDIR=${BINDIR}/dict
LINKS=	${FILESDIR}/web2 ${FILESDIR}/words
LINKSMODE= ${FILESMODE}

.include <bsd.prog.mk>
