#	$NetBSD$

INCS=	prop_array.h prop_bool.h prop_data.h prop_dictionary.h \
	prop_ingest.h prop_number.h prop_object.h prop_string.h \
	proplib.h plistref.h

INCSDIR=	/usr/include/prop

.include <bsd.prog.mk>
