#	$NetBSD$

.include <bsd.own.mk>

.PATH:	${X11SRCDIR.xc}/extras/freetype2/include/freetype/config

INCSDIR=${X11INCDIR}/freetype2/freetype/config

INCS=	ftconfig.h ftheader.h ftmodule.h ftoption.h ftstdlib.h

.include <bsd.x11.mk>
.include <bsd.prog.mk>
