#	$NetBSD$
#	from: @(#)Makefile	5.4 (Berkeley) 5/11/93

PROG=	timedc
SRCS=	cmds.c cmdtab.c timedc.c byteorder.c measure.c cksum.c tspname.c
MAN=	timedc.8
.PATH:	${.CURDIR}/../timed

.include <bsd.prog.mk>
