# $NetBSD$

.include <bsd.own.mk>

CONFIGFILES=\
		aliases \
		backup \
		changelist \
		devices \
		disklabels \
		ftpusers \
		group \
		homes \
		local \
		lvm \
		mtree \
		nfs \
		passwd \
		pkgs \
		pkg_signatures \
		pkg_vulnerabilities \
		rhosts \
		rootdotfiles \
		varmail
FILESDIR=	/etc/security.d
FILESMODE=	${NONBINMODE}

.include <bsd.prog.mk>
