# $NetBSD$

NOMAN=	# defined

.PATH: ${.CURDIR}/generated

# pull LOCALEDIR and other declarations
.include <bsd.own.mk>

LOCALEFILE=	LC_MONETARY
CATEGORY=	monetary

.include "${.CURDIR}/../Makefile.locale"
.include "${.CURDIR}/../Makefile.common"
