# $NetBSD$

# $FreeBSD: src/gnu/usr.bin/groff/src/devices/grotty/Makefile,v 1.4 2003/05/01 13:22:19 ru Exp $

DIST_SUBDIR=	src/devices/grotty

PROG_CXX=	grotty
SRCS=		tty.cpp
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
