#	$NetBSD$

.include <bsd.own.mk>

FONTSUBDIR=	TTF

FILES=		luximb.ttf luximbi.ttf luximr.ttf luximri.ttf \
		luxirb.ttf luxirbi.ttf luxirr.ttf luxirri.ttf \
		luxisb.ttf luxisbi.ttf luxisr.ttf luxisri.ttf

.PATH: ${X11SRCDIR.xc}/extras/fonts/Bitstream-Vera

FILES+=		Vera.ttf VeraBI.ttf VeraBd.ttf VeraIt.ttf \
		VeraMoBI.ttf VeraMoBd.ttf VeraMoIt.ttf VeraMono.ttf \
		VeraSe.ttf VeraSeBd.ttf

.include "../Makefile.scaled"

.include <bsd.x11.mk>
.include <bsd.prog.mk>
