# $NetBSD$

NOMAN=		# defined
NOLINT=		# defined

.include <bsd.own.mk>

LIB=			h_tls_dlopen
SRCS=			h_tls_dlopen.c

LIBDIR=		${TESTSBASE}/lib/libc/tls
SHLIBDIR=	${TESTSBASE}/lib/libc/tls
SHLIB_MAJOR=	1

LIBISCXX=	yes
LIBISMODULE=	yes

.include <bsd.lib.mk>
