#	$NetBSD$

NOMAN=

.include <bsd.own.mk>

FILES=		${UUDECODE_FILES}
FILESDIR=	/
FILESMODE=	${BINMODE}
UUDECODE_FILES=	pcs750.bin
CLEANFILES+=	pcs750.bin

all dependall: ${FILES}

.include <bsd.files.mk>
.include <bsd.prog.mk>
