#!/bin/sh -
#
#	$NetBSD$
#
# Generic script for power button events.  We simply attempt to
# shut the system down gracefully, and let the kernel handle
# the poweroff.
#
# Arguments passed by powerd(8):
#
#	device event

case "${2}" in
pressed)
	/sbin/shutdown -p now "power button pressed"
	exit 0
	;;

*)
	logger -p warning "${0}: unsupported event ${2} on device ${1}" >&1
	exit 1
	;;
esac
