#	$NetBSD$

.include <bsd.own.mk>

FILESDIR=	/usr/share/examples/pf
FILES=		ackpri faq-example1 faq-example2 faq-example3
FILES+=		queue1 queue2 queue3 queue4

.PATH:	${NETBSDSRCDIR}/dist/pf/share/pf

.include <bsd.prog.mk>
