#!/bin/sh -
#
#	$NetBSD$
#	@(#)daily	8.2 (Berkeley) 1/25/94
#

export PATH=/bin:/usr/bin:/sbin:/usr/sbin
umask 077

if [ -s /etc/daily.conf ]; then
	. /etc/daily.conf
fi
if [ -s /etc/pkgpath.conf ]; then
	. /etc/pkgpath.conf
fi

host="$(hostname)"
date="$(date)"
rcvar_manpage='daily.conf(5)'

pkg_admin=${pkg_admin:-/usr/sbin/pkg_admin}
pkg_info=${pkg_info:-/usr/sbin/pkg_info}

echo "To: ${MAILTO:-root}"
echo "Subject: $host daily output for $date"
echo ""

if [ -f /etc/rc.subr ]; then
	. /etc/rc.subr
else
	echo "Can't read /etc/rc.subr; aborting."
	exit 1;
fi

if [ -z "$MAILTO" -o "$USER" != "root" ]; then
	MAILTO=root
fi

if [ -n "${pkgdb_dir}" ]; then
	echo "WARNING: Setting pkgdb_dir in daily.conf(5) is deprecated"
	echo "WARNING: Please define PKG_DBDIR in pkg_install.conf(5) instead"
	_compat_K_flag="-K ${pkgdb_dir}"
fi

echo ""
echo "Uptime: $(uptime)"

# Uncommenting any of the finds below would open up a race condition attack
# based on symlinks, potentially allowing removal of any file on the system.
#
#echo ""
#echo "Removing scratch and junk files:"
#if [ -d /tmp -a ! -h /tmp ]; then
#	cd /tmp && {
#	find . -type f -atime +3 -exec rm -f -- {} \;
#	find . ! -name . -type d -mtime +1 -exec rmdir -- {} \; \
#	    >/dev/null 2>&1; }
#fi

#if [ -d /var/tmp -a ! -h /var/tmp ]; then
#	cd /var/tmp && {
#	find . ! -name . -atime +7 -exec rm -f -- {} \;
#	find . ! \( -name . -o -name vi.recover \) -type d \
#		-mtime +1 -exec rmdir -- {} \; \
#	    >/dev/null 2>&1; }
#fi

# Additional junk directory cleanup would go like this:
#if [ -d /scratch -a ! -h /scratch ]; then
#	cd /scratch && {
#	find . ! -name . -atime +1 -exec rm -f -- {} \;
#	find . ! -name . -type d -mtime +1 -exec rmdir -- {} \; \
#	    >/dev/null 2>&1; }
#fi

#if [ -d /var/rwho -a ! -h /var/rwho ] ; then
#	cd /var/rwho && {
#	find . ! -name . -mtime +7 -exec rm -f -- {} \; ; }
#fi

DAILYDIR=$(mktemp -d -t _daily) || exit 1

trap "/bin/rm -rf $DAILYDIR ; exit 0" EXIT INT QUIT

if ! cd "$DAILYDIR"; then
	echo "Can not cd to $DAILYDIR".
	exit 1
fi

TMP=daily.$$
TMP2=daily2.$$

if checkyesno find_core; then
	. /etc/daily.d/core
fi

if checkyesno run_msgs; then
	msgs -c
fi

if checkyesno expire_news && [ -f /etc/news.expire ]; then
	/etc/news.expire
fi

if checkyesno purge_accounting && [ -f /var/account/acct ]; then
	. /etc/daily.d/acct
fi

if checkyesno run_calendar; then
	. /etc/daily.d/calendar
fi

echo ""
echo "Checking subsystem status:"

if checkyesno check_disks; then
	. /etc/daily.d/disks
fi

if checkyesno check_mailq; then
	. /etc/daily.d/mailq
fi

rm -f $TMP

if checkyesno check_network; then
	. /etc/daily.d/network
fi

if checkyesno run_fsck; then
	. /etc/daily.d/fsck
fi

if checkyesno run_rdist && [ -f /etc/Distfile ]; then
	. /etc/daily.d/rdist
fi

. /etc/daily.d/pkg

if checkyesno run_security; then
	. /etc/daily.d/security
fi

if checkyesno run_skeyaudit; then
	. /etc/daily.d/skeyaudit
fi

if checkyesno run_makemandb; then
	. /etc/daily.d/makemandb
fi

. /etc/daily.d/local
