#!/bin/sh -
#
#	$NetBSD$
#	from: @(#)monthly	8.1 (Berkeley) 6/9/93
#

export PATH=/bin:/usr/bin:/sbin:/usr/sbin
umask 077

if [ -s /etc/monthly.conf ]; then
	. /etc/monthly.conf
fi

host="$(hostname)"
date="$(date)"
rcvar_manpage='monthly.conf(5)'

echo "To: ${MAILTO:-root}"
echo "Subject: $host monthly output for $date"
echo ""

MONTHLYDIR=$(mktemp -d -t _monthly) || exit 1

trap "/bin/rm -rf $MONTHLYDIR ; exit 0" EXIT INT QUIT PIPE

if ! cd "$MONTHLYDIR"; then
	echo "Can not cd to $MONTHLYDIR".
	exit 1
fi

TMP=monthly.$$

# echo ""
# echo "Doing login accounting:"
# ac -p | sort -nr +1

. /etc/monthly.d/local
