#!/bin/sh -
#
#	$NetBSD$
#	from: @(#)weekly	8.2 (Berkeley) 1/2/94
#

export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/libexec
umask 077

if [ -s /etc/weekly.conf ]; then
	. /etc/weekly.conf
fi

host="$(hostname)"
date="$(date)"
rcvar_manpage='weekly.conf(5)'

echo "To: ${MAILTO:-root}"
echo "Subject: $host weekly output for $date"
echo ""

if [ -f /etc/rc.subr ]; then
	. /etc/rc.subr
else
	echo "Can't read /etc/rc.subr; aborting."
	exit 1;
fi

WEEKLYDIR=$(mktemp -d -t _weekly) || exit 1

trap "/bin/rm -rf $WEEKLYDIR ; exit 0" EXIT INT QUIT PIPE

if ! cd "$WEEKLYDIR"; then
	echo "Can not cd to $WEEKLYDIR".
	exit 1
fi

TMP=weekly.$$

#echo ""
#echo "Removing old .o files:"
#find /usr/src -name '*.o' -atime +21 -print -a -exec rm -f {} \;

# see if /usr/src exists and is local
# before looking there for checked-out files

#if [ -d /usr/src -a \
#  -n "$(find -f /usr/src ! -fstype local -prune -or -type d -print -prune)" ];
#then
#	echo ""
#	echo "Looking for checked out files:"
#
#	TDIR=$(mktemp -d -t _checkout) || exit 1
#	trap "/bin/rm -rf $TDIR ; exit 0" EXIT INT QUIT
#	for file in $(find -f /usr/src ! -fstype local -prune -or \
#	    -name 'p.*' -print | egrep 'SCCS/p\.'); do
#		owner=$(awk '{ print $3 }' $file)
#		echo "$owner	$file"
#		echo $file >> "$TDIR/$owner"
#	done | sed -e 's,SCCS/p.,,'
#	if test -n "$(ls $TDIR)"; then
#		for file in $TDIR/*; do
#			sed -e 's,SCCS/p.,,' $file | \
#			    Mail -s 'checked out files' ${file##*/}
#		done
#	fi
#fi

if checkyesno rebuild_locatedb; then
	. /etc/weekly.d/locatedb
fi

if checkyesno rebuild_whatisdb; then
	. /etc/weekly.d/whatisdb
fi

if checkyesno rebuild_mandb; then
	. /etc/weekly.d/mandb
fi

. /etc/weekly.d/local
