#	$NetBSD$

HOSTPROGNAME=	${_TOOL_PREFIX}makefs
HOST_SRCDIR=	usr.sbin/makefs

HOST_CPPFLAGS+=	-I. -I${TOOLDIR}/include/nbinclude

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
