#	$NetBSD$

SUBDIR=		ramdisk .WAIT instkernel .WAIT bootfloppy.sysinst
# `floppy-root' cannot be used now, due to size issue.
#SUBDIR+=	bootfloppy.generic

TARGETS+=	release

.include <bsd.subdir.mk>
