# $NetBSD$

.include <bsd.own.mk>

LIB=		h_helper_symver_dso
SRCS=		h_helper_symver_dso0.c

LIBDIR=		${TESTSBASE}/libexec/ld.elf_so/h_helper_symver_dso0
SHLIBDIR=	${TESTSBASE}/libexec/ld.elf_so/h_helper_symver_dso0
SHLIB_MAJOR=	1

MKSTATICLIB=	no
MKPROFILE=	no
MKPICINSTALL=	no
MKLINT=		no

NOMAN=		# defined

FILESDIR=	${TESTSBASE}/libexec/ld.elf_so/h_helper_symver_dso0

.include <bsd.lib.mk>
