# $NetBSD$

# $FreeBSD: src/gnu/usr.bin/groff/src/libs/libdriver/Makefile,v 1.3 2003/05/01 13:22:19 ru Exp $

DIST_SUBDIR=	src/libs/libdriver

LIBISPRIVATE=	yes

LIB=		driver
SRCS=		input.cpp printer.cpp

.include <bsd.lib.mk>
