#	$NetBSD$

NOOBJ=	# defined

.include <bsd.own.mk>

.if ${MKSHARE} != "no"
FILES=	sup.jp.netbsd.org \
	sup.netbsd.org sup2.fr.netbsd.org
FILESDIR=/usr/share/examples/supfiles
.endif

.include <bsd.prog.mk>
