#	$NetBSD$
#
#	etc.mvmeppc/Makefile.inc -- mvmeppc-specific etc Makefile targets
#

# If you change the list of distributed kernels, don't forget
# to update the release documentation in distrib/notes/common/contents

KERNEL_SETS=		GENERIC
