#	$NetBSD$
#

INCS=	auth.h auth_unix.h clnt.h clnt_soc.h nettype.h \
	pmap_clnt.h pmap_prot.h pmap_rmt.h raw.h rpc.h \
	rpc_com.h rpc_msg.h rpcb_clnt.h rpcb_prot.h rpcent.h \
	svc.h svc_auth.h svc_soc.h types.h xdr.h
RPC_INCS=	rpcb_prot.h

INCSDIR=	/usr/include/rpc

.include <bsd.rpc.mk>
.include <bsd.prog.mk>
