# $NetBSD$

# $FreeBSD: src/gnu/usr.bin/groff/src/devices/grolbp/Makefile,v 1.4 2003/05/01 13:22:18 ru Exp $

DIST_SUBDIR=	src/devices/grolbp

PROG_CXX=	grolbp
SRCS=		lbp.cpp
CLEANFILES=	${MAN}
USETBL=

.include <bsd.prog.mk>
