#	$NetBSD$

# This is arguably wrong, but it's where it's been installed historically.
INCSDIR= /usr/include/dev/pckbc

# Only install includes which are used by userland
INCS=	pckbdreg.h

.include <bsd.kinc.mk>
