#	$NetBSD$
#

PROG=		rump_au-naturel
NOMAN=

ISRUMP=		# persuadertron

# Link in components to see which devices they create.  The
# following is an example.  You should see /dev/bpf.
#
#LDADD+= 	-lrumpdev_bpf -lrumpdev -lrumpnet_net -lrumpnet

.include <bsd.prog.mk>
