#	$NetBSD$
CDBASE=		catscd			# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE
CDKERNELS=	netbsd-INSTALL.aout netbsd
CDINSTKERNEL=	../../instkernel

.include "${.CURDIR}/../../../common/Makefile.bootcd"
