# $NetBSD$

.include <bsd.own.mk>

LIB=			h_tls_dynamic
SRCS=			h_tls_dynamic.c

LIBDIR=		${TESTSBASE}/lib/libc/tls
SHLIBDIR=	${TESTSBASE}/lib/libc/tls
SHLIB_MAJOR=	1

LIBISCXX=	yes
MKSTATICLIB=	no
MKPROFILE=	no
MKPICINSTALL=	no
MKLINT=		no

NOMAN=		# defined

.include <bsd.lib.mk>
