#	$NetBSD$

HOSTPROGNAME=	${MACHINE_GNU_PLATFORM}-lint
HOST_SRCDIR=	usr.bin/xlint/xlint
HOST_CPPFLAGS=	-DPATH_LIBEXEC=\"${TOOLDIR}/libexec\" \
		-DTARGET_PREFIX=\"${MACHINE_GNU_PLATFORM}-\"

.include "${.CURDIR}/../Makefile.host"
