#	$NetBSD$

.include <bsd.own.mk>

NOOBJ=	# defined
NOMAN=	# defined

SUBDIR=	ctype monetary numeric time messages

FILES=		locale.alias
FILESOWN=	${LOCALEOWN}
FILESGRP=	${LOCALEGRP}
FILESMODE=	${LOCALEMODE}
FILESDIR=	${LOCALEDIR}

.include <bsd.prog.mk>
.include <bsd.subdir.mk>
