#	$NetBSD$
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	kvm_mkdb
SRCS=	kvm_mkdb.c nlist.c nlist_aout.c nlist_coff.c nlist_ecoff.c \
	nlist_elf32.c nlist_elf64.c testdb.c
MAN=	kvm_mkdb.8

.include <bsd.prog.mk>
