#	$NetBSD$

.include "bsd.own.mk"

# Run "${TOOLDIR}/bin/nbmake-${MACHINE} -f Makefile.regen" by hand after
# editing configure.ac.  See more detailed instructions in configure.ac.
regen:
	cd ${.CURDIR} && ${TOOLDIR}/bin/${_TOOL_PREFIX}autoconf
