#	$NetBSD$

.include <bsd.own.mk>

.PATH: ${NETBSDSRCDIR}/dist/pppd/pppstats

PROG=	pppstats
MAN=	pppstats.8
LINKS=  ${BINDIR}/pppstats ${BINDIR}/slstats
MLINKS=	pppstats.8 slstats.8

.include <bsd.prog.mk>
