#	$NetBSD$
#
# Public Domain.
#

.PATH:	${.CURDIR}/../../../../external/bsd/sljit/sljit \
	${.CURDIR}/../../../../external/bsd/sljit/dist/sljit_src

LIB=	rumpkern_sljit

SRCS=	sljitLir.c sljit_mod.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
