# $NetBSD$

.include <bsd.own.mk>

CONFIGFILES=\
		acct \
		calendar \
		core \
		disks \
		fsck \
		local \
		mailq \
		makemandb \
		network \
		pkg \
		rdist \
		security \
		skeyaudit
FILESDIR=	/etc/daily.d
FILESMODE=	${NONBINMODE}

.include <bsd.prog.mk>
