# $NetBSD$

CONFIGFILES=	README display_manager ftpd gdm imap kde login other passwd \
		pop3 ppp rexecd rsh sshd su system telnetd xdm xserver
FILESDIR=	/etc/pam.d
FILESMODE=	644
FILESMODE_README=444

.include <bsd.prog.mk>
