#!/bin/sh
#	$NetBSD$
# Generate a shaved down protocols file for install media.
#
echo "#	\$NetBSD\$" > protocols
echo "# Shaved down /etc/protocols for installation media" >> protocols
/usr/bin/sed -e 's/#.*//' -e '/^$/d' -e 's/ *$//' -e 's/  */ /' ../../etc/protocols >> protocols
