#	$NetBSD$	

NOOBJ=		# defined

.include <bsd.own.mk>

.PATH:	${NETBSDSRCDIR}/lib/libedit

INCS=		readline.h
INCSDIR=	/usr/include/readline
INCSYMLINKS=	readline.h ${INCSDIR}/history.h

.include <bsd.prog.mk>
