#	$NetBSD$

XMODULEDIR=	${X11USRLIBDIR}/modules/extensions

.include "../../../Makefile.serverlib"

.include <bsd.own.mk>

.PATH:		${X11SRCDIR.xc}/programs/Xserver/GL/mesa/GLcore
SRCS=		GLcoremodule.c

.include "../Makefile.GLcore"
