#	$NetBSD$

#
# Note that the directory 'tostools' should never show up...
#
SUBDIR=	libsa .WAIT ahdilabel binpatch bootpref bootxx bootxxx edahdi \
	installboot keymaps loadkmap msconfig xxboot

.include <bsd.subdir.mk>
