#	$NetBSD$

# use 'make -f Makefile.tcdevs' to make tcdevs.h and tcdevs_data.h

INCSDIR= /usr/include/dev/tc

# Only install includes which are used by userland
INCS=	sfbreg.h sticio.h sticreg.h

.include <bsd.kinc.mk>
