#	$NetBSD$

# Makefile fragment to build a (32 or 64 bit) libldd_elfxx.a.
# Expects CPPFLAGS to have ELFSIZE set, and LIB to be set.

SRCS=	ldd_elfxx.c
SRCS+=	xmalloc.c debug.c expand.c map_object.c load.c search.c \
	headers.c paths.c tls.c symver.c

.include "Makefile.common"
