#	$NetBSD$

.include <bsd.own.mk>

.PATH:	${X11SRCDIR.xc}/extras/freetype2/include/freetype/internal/services

INCSDIR=${X11INCDIR}/freetype2/freetype/internal/services

INCS=	svbdf.h svgldict.h svmm.h svpfr.h svpostnm.h svpscmap.h svpsinfo.h \
	svsfnt.h svttcmap.h svwinfnt.h svxf86nm.h

.include <bsd.x11.mk>
.include <bsd.prog.mk>
