#	$NetBSD$

PROG=	mailwrapper
MAN=	mailwrapper.8 mailer.conf.5

SYMLINKS= 	/usr/sbin/mailwrapper /usr/sbin/sendmail  \
		/usr/sbin/mailwrapper /usr/bin/newaliases \
		/usr/sbin/mailwrapper /usr/bin/mailq \
		/usr/sbin/mailwrapper /usr/bin/hoststat \
		/usr/sbin/mailwrapper /usr/bin/purgestat

.include <bsd.prog.mk>
