#	$NetBSD$
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

.include <bsd.own.mk>

PROG=	wump
MAN=	wump.6
HIDEGAME=hidegame
.if ${MKSHARE} != "no"
FILES=wump.info
FILESDIR=/usr/share/games
.endif

.include <bsd.prog.mk>
