# $NetBSD$

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.bin/config
ATFFILE=	no

FILESDIR=	${TESTSDIR}/support/conf
FILES=		files

.include <bsd.test.mk>
.include <bsd.files.mk>
.include <bsd.prog.mk>
