#	$NetBSD$

HOSTPROGNAME=	${_TOOL_PREFIX}paxctl
HOST_SRCDIR=	usr.sbin/paxctl

HOST_CPPFLAGS+=	-I${TOOLDIR}/include/nbinclude

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
