#	$NetBSD$

PROG=	huntd
SRCS=	answer.c ctl.c ctl_transact.c draw.c driver.c execute.c expl.c \
	extern.c faketalk.c get_names.c makemaze.c pathname.c shots.c terminal.c
MAN=	huntd.6

.include <bsd.prog.mk>
