#	$NetBSD$

.ifndef _MAKEFILE_OPENSSL_INCLUDED
_MAKEFILE_OPENSSL_INCLUDED=1

.include <bsd.own.mk>

OPENSSLSRC=	${CRYPTODIST}/external/bsd/openssl/dist
CPPFLAGS+=	-DOPENSSLDIR=\"/etc/openssl\"
CPPFLAGS+=	-DENGINESDIR=\"/usr/lib/openssl\"
CPPFLAGS+=	-DDSO_DLFCN -DHAVE_DLFCN_H

.endif
