#	$NetBSD$

# first stage bootloader
SUBDIR+=	bootxx_ffs
SUBDIR+=	bootxx_cd9660
#SUBDIR+=	bootxx_lfs

# second stage bootloader
SUBDIR+=	boot

# program to install bootstrap
SUBDIR+=	installboot

.include <bsd.subdir.mk>
