#	$NetBSD$
#
# Makefile for hpcsh
#

MENUS_MD=	menus.md.${SYSINSTLANG} menus.mbr
MSG_MD=		msg.md.${SYSINSTLANG} msg.mbr.${SYSINSTLANG}

LANGUAGES=	# no translations ready yet

.include "../../Makefile.inc"
