#	$NetBSD$

HOSTPROGNAME=	nbdisklabel
HOST_SRCDIR=	sbin/disklabel
HOST_SRCS=	disklabel.c

NOMAN=	# defined

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"

.PATH: ${.CURDIR}/../../lib/libc/gen
