# $NetBSD$

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.bin/config
ATFFILE=	no

FILESDIR=	${TESTSDIR}/support/arch/regress/conf
FILES=		Makefile.regress
FILES+=		files.regress
FILES+=		std.regress

.include <bsd.test.mk>
.include <bsd.files.mk>
.include <bsd.prog.mk>
