#	$NetBSD$

INCSDIR= /usr/include/macppc

# Add the macppc specific includes.

INCS=	adbsys.h apmvar.h autoconf.h \
	disklabel.h \
	grfioctl.h \
	intr.h \
	keyboard.h \
	sljitarch.h \
	vmparam.h

.include "../../powerpc/include/Makefile"
