#	$NetBSD$

MAN=	autoconf.4 clmpcc.4 clock.4 ie.4 intro.4 lpt.4 mainbus.4 \
	mem.4 memc.4 ncrsc.4 pcc.4 pcctwo.4 wdsc.4 zsc.4
MLINKS= mem.4 kmem.4
MLINKS+=lpt.4 lpa.4
MANSUBDIR=/mvme68k

.include <bsd.man.mk>
