# $NetBSD$

.include <bsd.own.mk>

# XXX catpages conflicts with the corresponding phony target name
CONFIGFILES=\
		atf \
		bluetooth \
		./catpages \
		ddbonpanic \
		defaults \
		dhcpcd \
		dhcpcdrundir \
		envsys \
		fontconfig \
		gid \
		gpio \
		hosts \
		iscsi \
		mailerconf \
		makedev \
		motd \
		mtree \
		named \
		obsolete \
		pam \
		periodic \
		pf \
		ptyfsoldnodes \
		pwd_mkdb \
		rc \
		sendmail \
		ssh \
		tcpdumpchroot \
		uid \
		varrwho \
		varshm \
		wscons \
		x11 \
		xkb
FILESDIR=	/etc/install.d
FILESMODE=	${NONBINMODE}

.include <bsd.prog.mk>
