#	$NetBSD$
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	locate
MAN=	locate.1 locate.updatedb.8

FILES=updatedb.sh
FILESNAME=locate.updatedb
FILESDIR=/usr/libexec
FILESMODE=${BINMODE}

.include <bsd.prog.mk>
