#	$NetBSD$

# NOTE: <bsd.own.mk> needs to be previously .included for NETBSDSRCDIR

SIGINFO_H= ${DESTDIR}/usr/include/sys/siginfo.h
siginfo.c: mksiginfos ${SIGINFO_H}
	${_MKTARGET_CREATE}
	AWK=${TOOL_AWK:Q} DESTDIR=${DESTDIR} \
	${HOST_SH} ${NETBSDSRCDIR}/usr.bin/kdump/mksiginfos > siginfo.c

DPSRCS+= siginfo.c


${SIGINFO_H}: .PRECIOUS
